import {
    Zap, Wrench, Droplets, Thermometer, Sparkles, Hammer,
    Smartphone, BookOpen, Leaf, Paintbrush, Video, Grid,
    HardHat, AlertTriangle, Briefcase, Car, ShowerHead,
    Truck, Dumbbell, Heart, PartyPopper, Camera, Scissors,
    Lock, Package, Users, ShieldCheck, Siren, Stethoscope, Sun,
    Snowflake, Battery, User, Layout,
    type LucideIcon
} from "lucide-react";

export interface ServiceCategory {
    id: string;
    name: string;
    nameKey: string;
    emoji: string;
    icon: LucideIcon;
    iconName: string;
    color: string;
    description: string;
    descriptionKey: string;
    stats?: {
        totalWorkers: number;
        activeJobs: number;
        growth?: number;
    };
}

export interface ServiceItem {
    id: string;
    title: string;
    titleKey: string;
    category: string;
    categoryId: string;
    desc: string;
    descKey: string;
    icon: LucideIcon;
    color: string;
    image: string;
    startingPrice: number;
    isEmergency?: boolean;
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
    {
        id: "mechanic",
        name: "Mechanic",
        nameKey: "categories.mechanic.name",
        emoji: "👨‍🔧",
        icon: Wrench,
        iconName: "Wrench",
        color: "bg-slate-50 text-slate-700 border-slate-200",
        description: "Professional vehicle repair and diagnostics.",
        descriptionKey: "categories.mechanic.desc"
    },
    {
        id: "electrician",
        name: "Electrician",
        nameKey: "categories.electrician.name",
        emoji: "⚡",
        icon: Zap,
        iconName: "Zap",
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        description: "Electrical wiring, installation and repairs.",
        descriptionKey: "categories.electrician.desc"
    },
    {
        id: "plumber",
        name: "Plumber",
        nameKey: "categories.plumber.name",
        emoji: "🚰",
        icon: Droplets,
        iconName: "Droplets",
        color: "bg-blue-50 text-blue-600 border-blue-100",
        description: "Plumbing, leak fixes and fixture installations.",
        descriptionKey: "categories.plumber.desc"
    },
    {
        id: "painting",
        name: "Painting",
        nameKey: "categories.painting.name",
        emoji: "🎨",
        icon: Paintbrush,
        iconName: "Paintbrush",
        color: "bg-orange-50 text-orange-600 border-orange-100",
        description: "Interior and exterior professional painting.",
        descriptionKey: "categories.painting.desc"
    },
    {
        id: "appliance-repair",
        name: "Appliance Repair",
        nameKey: "categories.appliance-repair.name",
        emoji: "🔧",
        icon: Smartphone,
        iconName: "Smartphone",
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        description: "Home appliance maintenance and repair.",
        descriptionKey: "categories.appliance-repair.desc"
    },
    {
        id: "construction",
        name: "Construction",
        nameKey: "categories.construction.name",
        emoji: "🏗️",
        icon: HardHat,
        iconName: "HardHat",
        color: "bg-amber-50 text-amber-600 border-amber-100",
        description: "New construction and renovation services.",
        descriptionKey: "categories.construction.desc"
    },
    {
        id: "ac-installation",
        name: "AC Installation",
        nameKey: "categories.ac-installation.name",
        emoji: "❄️",
        icon: Snowflake,
        iconName: "Snowflake",
        color: "bg-blue-50 text-blue-700 border-blue-100",
        description: "Professional AC installation and servicing.",
        descriptionKey: "categories.ac-installation.desc"
    },
    {
        id: "solar-installation",
        name: "Solar Installation",
        nameKey: "categories.solar-installation.name",
        emoji: "☀️",
        icon: Sun,
        iconName: "Sun",
        color: "bg-yellow-50 text-yellow-700 border-yellow-200",
        description: "Green energy and solar power solutions.",
        descriptionKey: "categories.solar-installation.desc"
    },
    {
        id: "cctv-installation",
        name: "CCTV Installation",
        nameKey: "categories.cctv-installation.name",
        emoji: "📹",
        icon: Video,
        iconName: "Video",
        color: "bg-gray-50 text-gray-800 border-gray-200",
        description: "Security surveillance and camera setups.",
        descriptionKey: "categories.cctv-installation.desc"
    },
    {
        id: "security",
        name: "Security",
        nameKey: "categories.security.name",
        emoji: "🛡️",
        icon: ShieldCheck,
        iconName: "ShieldCheck",
        color: "bg-red-50 text-red-700 border-red-100",
        description: "Professional security and guarding services.",
        descriptionKey: "categories.security.desc"
    },
    {
        id: "gardening",
        name: "Gardening",
        nameKey: "categories.gardening.name",
        emoji: "🏡",
        icon: Leaf,
        iconName: "Leaf",
        color: "bg-green-50 text-green-700 border-green-100",
        description: "Landscaping and garden maintenance.",
        descriptionKey: "categories.gardening.desc"
    },
    {
        id: "cleaning",
        name: "Cleaning",
        nameKey: "categories.cleaning.name",
        emoji: "🧹",
        icon: Sparkles,
        iconName: "Sparkles",
        color: "bg-blue-50 text-blue-500 border-blue-100",
        description: "Deep cleaning and sanitation services.",
        descriptionKey: "categories.cleaning.desc"
    },
    {
        id: "automotive",
        name: "Automotive",
        nameKey: "categories.automotive.name",
        emoji: "🚗",
        icon: Car,
        iconName: "Car",
        color: "bg-zinc-50 text-zinc-800 border-zinc-200",
        description: "Car detailing and periodic maintenance.",
        descriptionKey: "categories.automotive.desc"
    },
    {
        id: "health-medical",
        name: "Health & Medical",
        nameKey: "categories.health-medical.name",
        emoji: "⚕️",
        icon: Stethoscope,
        iconName: "Stethoscope",
        color: "bg-emerald-50 text-emerald-700 border-emerald-100",
        description: "In-home healthcare and medical support.",
        descriptionKey: "categories.health-medical.desc"
    },
    {
        id: "emergency-assistance",
        name: "Emergency Assistance",
        nameKey: "categories.emergency-assistance.name",
        emoji: "🚨",
        icon: Siren,
        iconName: "Siren",
        color: "bg-red-50 text-red-600 border-red-100",
        description: "24/7 roadside and safety emergency help.",
        descriptionKey: "categories.emergency-assistance.desc"
    },
    {
        id: "education",
        name: "Education Services",
        nameKey: "categories.education.name",
        emoji: "📚",
        icon: BookOpen,
        iconName: "BookOpen",
        color: "bg-purple-50 text-purple-700 border-purple-100",
        description: "Tutoring and skill development programs.",
        descriptionKey: "categories.education.desc"
    },
    {
        id: "event-management",
        name: "Event Management",
        nameKey: "categories.event-management.name",
        emoji: "🎈",
        icon: PartyPopper,
        iconName: "PartyPopper",
        color: "bg-indigo-50 text-indigo-700 border-indigo-100",
        description: "Planning and execution of your special events.",
        descriptionKey: "categories.event-management.desc"
    },
    {
        id: "transport",
        name: "Transport Services",
        nameKey: "categories.transport.name",
        emoji: "🚚",
        icon: Truck,
        iconName: "Truck",
        color: "bg-zinc-100 text-zinc-900 border-zinc-300",
        description: "Moving, cargo and rental transport solutions.",
        descriptionKey: "categories.transport.desc"
    },
    {
        id: "beauty-salon",
        name: "Beauty & Salon",
        nameKey: "categories.beauty-salon.name",
        emoji: "✂️",
        icon: Scissors,
        iconName: "Scissors",
        color: "bg-pink-50 text-pink-700 border-pink-100",
        description: "Salon and grooming services at your home.",
        descriptionKey: "categories.beauty-salon.desc"
    },
    {
        id: "tour",
        name: "Tour",
        nameKey: "categories.tour.name",
        emoji: "✈️",
        icon: Layout,
        iconName: "Layout",
        color: "bg-teal-50 text-teal-700 border-teal-100",
        description: "Travel planning and international booking.",
        descriptionKey: "categories.tour.desc"
    },
    {
        id: "agriculture",
        name: "Agriculture",
        nameKey: "categories.agriculture.name",
        emoji: "🌾",
        icon: Grid,
        iconName: "Grid",
        color: "bg-lime-50 text-lime-800 border-lime-200",
        description: "Smart farming and agricultural equipment.",
        descriptionKey: "categories.agriculture.desc"
    }
];

export const SERVICES_LIST: ServiceItem[] = [
    // 1) Mechanic
    {
        id: "engine-diagnostics",
        title: "Engine Diagnostics",
        titleKey: "services.Engine Diagnostics",
        category: "Mechanic",
        categoryId: "mechanic",
        desc: "Professional diagnostic scanning and engine health check.",
        descKey: "Professional diagnostic scanning and engine health check.",
        icon: Wrench,
        color: "bg-slate-50 text-slate-700 border-slate-200",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500
    },
    {
        id: "brake-suspension-repair",
        title: "Brake & Suspension Repair",
        titleKey: "services.Brake & Suspension Repair",
        category: "Mechanic",
        categoryId: "mechanic",
        desc: "Brake pad replacement and suspension system tuning.",
        descKey: "Brake pad replacement and suspension system tuning.",
        icon: Wrench,
        color: "bg-slate-50 text-slate-700 border-slate-200",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },
    {
        id: "general-tuning",
        title: "General Tuning",
        titleKey: "services.General Tuning",
        category: "Mechanic",
        categoryId: "mechanic",
        desc: "Complete vehicle tuning for optimal performance.",
        descKey: "Complete vehicle tuning for optimal performance.",
        icon: Wrench,
        color: "bg-slate-50 text-slate-700 border-slate-200",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1200
    },

    // 2) Electrician
    {
        id: "wiring-circuit-repair",
        title: "Wiring & Circuit Repair",
        titleKey: "services.Wiring & Circuit Repair",
        category: "Electrician",
        categoryId: "electrician",
        desc: "Internal wiring fixes and circuit board repairs.",
        descKey: "Internal wiring fixes and circuit board repairs.",
        icon: Zap,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 800
    },
    {
        id: "fan-light-installation",
        title: "Fan & Light Installation",
        titleKey: "services.Fan & Light Installation",
        category: "Electrician",
        categoryId: "electrician",
        desc: "Safe installation of ceiling fans and light fixtures.",
        descKey: "Safe installation of ceiling fans and light fixtures.",
        icon: Zap,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 500
    },
    {
        id: "ups-inverter-maintenance",
        title: "UPS & Inverter Maintenance",
        titleKey: "services.UPS & Inverter Maintenance",
        category: "Electrician",
        categoryId: "electrician",
        desc: "Regular servicing and repair of UPS systems.",
        descKey: "Regular servicing and repair of UPS systems.",
        icon: Zap,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1000
    },

    // 3) Plumber
    {
        id: "leakage-pipe-repair",
        title: "Leakage & Pipe Repair",
        titleKey: "services.Leakage & Pipe Repair",
        category: "Plumber",
        categoryId: "plumber",
        desc: "Fixing water leaks and repairing damaged pipes.",
        descKey: "Fixing water leaks and repairing damaged pipes.",
        icon: Droplets,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 600
    },
    {
        id: "bathroom-fixture-installation",
        title: "Bathroom Fixture Installation",
        titleKey: "services.Bathroom Fixture Installation",
        category: "Plumber",
        categoryId: "plumber",
        desc: "Installation of taps, showers, and bathroom sets.",
        descKey: "Installation of taps, showers, and bathroom sets.",
        icon: Droplets,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500
    },
    {
        id: "motor-pump-repair",
        title: "Motor & Pump Repair",
        titleKey: "services.Motor & Pump Repair",
        category: "Plumber",
        categoryId: "plumber",
        desc: "Repairing water motors and pressure pumps.",
        descKey: "Repairing water motors and pressure pumps.",
        icon: Droplets,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },

    // 4) Painting
    {
        id: "interior-wall-painting",
        title: "Interior Wall Painting",
        titleKey: "services.Interior Wall Painting",
        category: "Painting",
        categoryId: "painting",
        desc: "Premium interior painting for rooms and halls.",
        descKey: "Premium interior painting for rooms and halls.",
        icon: Paintbrush,
        color: "bg-orange-50 text-orange-600 border-orange-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "exterior-weather-sheet",
        title: "Exterior & Weather Sheet",
        titleKey: "services.Exterior & Weather Sheet",
        category: "Painting",
        categoryId: "painting",
        desc: "Weather-resistant exterior wall painting.",
        descKey: "Weather-resistant exterior wall painting.",
        icon: Paintbrush,
        color: "bg-orange-50 text-orange-600 border-orange-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 5000
    },
    {
        id: "wood-polish-varnish",
        title: "Wood Polish & Varnish",
        titleKey: "services.Wood Polish & Varnish",
        category: "Painting",
        categoryId: "painting",
        desc: "High-quality polish for furniture and doors.",
        descKey: "High-quality polish for furniture and doors.",
        icon: Paintbrush,
        color: "bg-orange-50 text-orange-600 border-orange-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2500
    },

    // 5) Appliance Repair
    {
        id: "refrigerator-freezer-repair",
        title: "Refrigerator & Freezer Repair",
        titleKey: "services.Refrigerator & Freezer Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Gas refilling and cooling system repairs.",
        descKey: "Gas refilling and cooling system repairs.",
        icon: Smartphone,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500
    },
    {
        id: "washing-machine-service",
        title: "Washing Machine Service",
        titleKey: "services.Washing Machine Service",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Mechanical and electrical repairs for washing machines.",
        descKey: "Mechanical and electrical repairs for washing machines.",
        icon: Smartphone,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1200
    },

    // 6) Construction
    {
        id: "general-construction-sub",
        title: "Construction",
        titleKey: "services.Construction",
        category: "Construction",
        categoryId: "construction",
        desc: "New building and structural construction.",
        descKey: "New building and structural construction.",
        icon: HardHat,
        color: "bg-amber-50 text-amber-600 border-amber-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 100000
    },
    {
        id: "home-renovation",
        title: "Home Renovation",
        titleKey: "services.Home Renovation",
        category: "Construction",
        categoryId: "construction",
        desc: "Modernizing and upgrading existing spaces.",
        descKey: "Modernizing and upgrading existing spaces.",
        icon: HardHat,
        color: "bg-amber-50 text-amber-600 border-amber-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 50000
    },
    {
        id: "concrete-work",
        title: "Concrete Work",
        titleKey: "services.Concrete Work",
        category: "Construction",
        categoryId: "construction",
        desc: "Professional slab and foundational concrete work.",
        descKey: "Professional slab and foundational concrete work.",
        icon: HardHat,
        color: "bg-amber-50 text-amber-600 border-amber-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 15000
    },
    {
        id: "tile-marble-fitting",
        title: "Tile & Marble Fitting",
        titleKey: "services.Tile & Marble Fitting",
        category: "Construction",
        categoryId: "construction",
        desc: "Precision floor and wall tile installation.",
        descKey: "Precision floor and wall tile installation.",
        icon: HardHat,
        color: "bg-amber-50 text-amber-600 border-amber-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 8000
    },
    {
        id: "ceiling-design",
        title: "Ceiling Design",
        titleKey: "services.Ceiling Design",
        category: "Construction",
        categoryId: "construction",
        desc: "Decorative false ceiling and plaster work.",
        descKey: "Decorative false ceiling and plaster work.",
        icon: HardHat,
        color: "bg-amber-50 text-amber-600 border-amber-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 5000
    },

    // 7) AC Installation
    {
        id: "ac-installation-service",
        title: "AC Installation",
        titleKey: "services.AC Installation",
        category: "AC Installation",
        categoryId: "ac-installation",
        desc: "Expert Split and Inverter AC installation.",
        descKey: "Expert Split and Inverter AC installation.",
        icon: Snowflake,
        color: "bg-blue-50 text-blue-700 border-blue-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 3500
    },

    // 8) Solar Installation
    {
        id: "solar-panel-setup",
        title: "Solar Panel Setup",
        titleKey: "services.Solar Panel Setup",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Complete solar panel mounting and wiring.",
        descKey: "Complete solar panel mounting and wiring.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-700 border-yellow-200",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 15000
    },
    {
        id: "inverter-programming",
        title: "Inverter Programming",
        titleKey: "services.Inverter Programming",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Configuration and tuning of solar inverters.",
        descKey: "Configuration and tuning of solar inverters.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-700 border-yellow-200",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "battery-health-check",
        title: "Battery Health Check",
        titleKey: "services.Battery Health Check",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Maintenance and health testing for solar batteries.",
        descKey: "Maintenance and health testing for solar batteries.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-700 border-yellow-200",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1000
    },

    // 9) CCTV Installation
    {
        id: "cctv-setup",
        title: "CCTV Installation",
        titleKey: "services.CCTV Installation",
        category: "CCTV Installation",
        categoryId: "cctv-installation",
        desc: "Full security camera and DVR/NVR setup.",
        descKey: "Full security camera and DVR/NVR setup.",
        icon: Video,
        color: "bg-gray-50 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 5000
    },

    // 10) Security
    {
        id: "guard-services",
        title: "Guard Services",
        titleKey: "services.Guard Services",
        category: "Security",
        categoryId: "security",
        desc: "Professional physical security for homes and offices.",
        descKey: "Professional physical security for homes and offices.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-700 border-red-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 25000
    },
    {
        id: "smart-lock-installation",
        title: "Smart Lock Installation",
        titleKey: "services.Smart Lock Installation",
        category: "Security",
        categoryId: "security",
        desc: "Installation of digital and biometric smart locks.",
        descKey: "Installation of digital and biometric smart locks.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-700 border-red-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 4000
    },

    // 11) Gardening
    {
        id: "lawn-mowing-trimming",
        title: "Lawn Mowing & Trimming",
        titleKey: "services.Lawn Mowing & Trimming",
        category: "Gardening",
        categoryId: "gardening",
        desc: "Professional grass cutting and hedge trimming.",
        descKey: "Professional grass cutting and hedge trimming.",
        icon: Leaf,
        color: "bg-green-50 text-green-700 border-green-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1000
    },
    {
        id: "plantation-soil-care",
        title: "Plantation & Soil Care",
        titleKey: "services.Plantation & Soil Care",
        category: "Gardening",
        categoryId: "gardening",
        desc: "Flower planting and soil fertilization services.",
        descKey: "Flower planting and soil fertilization services.",
        icon: Leaf,
        color: "bg-green-50 text-green-700 border-green-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500
    },
    {
        id: "pest-control-gardens",
        title: "Pest Control for Gardens",
        titleKey: "services.Pest Control for Gardens",
        category: "Gardening",
        categoryId: "gardening",
        desc: "Eliminating pests and protecting your plants.",
        descKey: "Eliminating pests and protecting your plants.",
        icon: Leaf,
        color: "bg-green-50 text-green-700 border-green-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },

    // 12) Cleaning
    {
        id: "full-house-deep-cleaning",
        title: "Full House Deep Cleaning",
        titleKey: "services.Full House Deep Cleaning",
        category: "Cleaning",
        categoryId: "cleaning",
        desc: "Complete sanitization and deep cleaning of entire home.",
        descKey: "Complete sanitization and deep cleaning of entire home.",
        icon: Sparkles,
        color: "bg-blue-50 text-blue-500 border-blue-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 10000
    },
    {
        id: "water-tank-cleaning",
        title: "Water Tank Cleaning",
        titleKey: "services.Water Tank Cleaning",
        category: "Cleaning",
        categoryId: "cleaning",
        desc: "Sanitizing underground and overhead water tanks.",
        descKey: "Sanitizing underground and overhead water tanks.",
        icon: Sparkles,
        color: "bg-blue-50 text-blue-500 border-blue-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "sofa-carpet-cleaning",
        title: "Sofa & Carpet Cleaning",
        titleKey: "services.Sofa & Carpet Cleaning",
        category: "Cleaning",
        categoryId: "cleaning",
        desc: "Steam cleaning for sofas, carpets, and upholstery.",
        descKey: "Steam cleaning for sofas, carpets, and upholstery.",
        icon: Sparkles,
        color: "bg-blue-50 text-blue-500 border-blue-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 2500
    },

    // 13) Automotive
    {
        id: "car-wash-detailing",
        title: "Car Wash & Detailing",
        titleKey: "services.Car Wash & Detailing",
        category: "Automotive",
        categoryId: "automotive",
        desc: "Premium exterior wash and interior detailing.",
        descKey: "Premium exterior wash and interior detailing.",
        icon: Car,
        color: "bg-zinc-50 text-zinc-800 border-zinc-200",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500
    },
    {
        id: "oil-filter-change",
        title: "Oil & Filter Change",
        titleKey: "services.Oil & Filter Change",
        category: "Automotive",
        categoryId: "automotive",
        desc: "Engine oil replacement and filter maintenance.",
        descKey: "Engine oil replacement and filter maintenance.",
        icon: Car,
        color: "bg-zinc-50 text-zinc-800 border-zinc-200",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 4000
    },
    {
        id: "battery-replacement-auto",
        title: "Battery Replacement",
        titleKey: "services.Battery Replacement",
        category: "Automotive",
        categoryId: "automotive",
        desc: "New battery installation and electrical check.",
        descKey: "New battery installation and electrical check.",
        icon: Car,
        color: "bg-zinc-50 text-zinc-800 border-zinc-200",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 8000
    },
    {
        id: "car-modification",
        title: "Car Modification",
        titleKey: "services.Car Modification",
        category: "Automotive",
        categoryId: "automotive",
        desc: "Custom upgrades and aesthetic modifications.",
        descKey: "Custom upgrades and aesthetic modifications.",
        icon: Car,
        color: "bg-zinc-50 text-zinc-800 border-zinc-200",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 10000
    },

    // 14) Health & Medical
    {
        id: "home-nursing-care",
        title: "Home Nursing Care",
        titleKey: "services.Home Nursing Care",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Qualified nurses for at-home patient care.",
        descKey: "Qualified nurses for at-home patient care.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-700 border-emerald-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "physiotherapy-sessions",
        title: "Physiotherapy Sessions",
        titleKey: "services.Physiotherapy Sessions",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Expert physiotherapy for recovery and mobility.",
        descKey: "Expert physiotherapy for recovery and mobility.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-700 border-emerald-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },
    {
        id: "lab-test-sample-collection",
        title: "Lab Test Sample Collection",
        titleKey: "services.Lab Test Sample Collection",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Hassle-free blood and sample collection at home.",
        descKey: "Hassle-free blood and sample collection at home.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-700 border-emerald-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 500
    },

    // 15) Emergency Assistance
    {
        id: "roadside-recovery",
        title: "Roadside Recovery",
        titleKey: "services.Roadside Recovery",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Immediate towing and breakdown recovery.",
        descKey: "Immediate towing and breakdown recovery.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "fire-safety-equipment",
        title: "Fire Safety Equipment",
        titleKey: "services.Fire Safety Equipment",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Installation and servicing of fire extinguishers.",
        descKey: "Installation and servicing of fire extinguishers.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 2000
    },

    // 16) Education Services
    {
        id: "home-tuition-k12",
        title: "Home Tuition (K-12)",
        titleKey: "services.Home Tuition (K-12)",
        category: "Education Services",
        categoryId: "education",
        desc: "Expert home tutors for school and college subjects.",
        descKey: "Expert home tutors for school and college subjects.",
        icon: BookOpen,
        color: "bg-purple-50 text-purple-700 border-purple-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 5000
    },
    {
        id: "language-learning-edu",
        title: "Language Learning",
        titleKey: "services.Language Learning",
        category: "Education Services",
        categoryId: "education",
        desc: "Language learning and communication skills.",
        descKey: "Language learning and communication skills.",
        icon: BookOpen,
        color: "bg-purple-50 text-purple-700 border-purple-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 3000
    },
    {
        id: "computer-it-skills",
        title: "Computer & IT Skills",
        titleKey: "services.Computer & IT Skills",
        category: "Education Services",
        categoryId: "education",
        desc: "Basic to advanced computer and IT training.",
        descKey: "Basic to advanced computer and IT training.",
        icon: BookOpen,
        color: "bg-purple-50 text-purple-700 border-purple-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 4000
    },
    {
        id: "garden-design",
        title: "Garden Design",
        titleKey: "services.Garden Design",
        category: "Gardening Services",
        categoryId: "gardening-services",
        desc: "Professional garden design by verified experts.",
        descKey: "Professional garden design by verified experts.",
        icon: Leaf,
        color: "bg-green-50 text-green-600 border-green-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "tree-trimming",
        title: "Tree Trimming",
        titleKey: "services.Tree Trimming",
        category: "Gardening Services",
        categoryId: "gardening-services",
        desc: "Professional tree trimming by verified experts.",
        descKey: "Professional tree trimming by verified experts.",
        icon: Leaf,
        color: "bg-green-50 text-green-600 border-green-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "grass-cutting",
        title: "Grass Cutting",
        titleKey: "services.Grass Cutting",
        category: "Gardening Services",
        categoryId: "gardening-services",
        desc: "Professional grass cutting by verified experts.",
        descKey: "Professional grass cutting by verified experts.",
        icon: Leaf,
        color: "bg-green-50 text-green-600 border-green-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "irrigation-setup",
        title: "Irrigation Setup",
        titleKey: "services.Irrigation Setup",
        category: "Gardening Services",
        categoryId: "gardening-services",
        desc: "Professional irrigation setup by verified experts.",
        descKey: "Professional irrigation setup by verified experts.",
        icon: Leaf,
        color: "bg-green-50 text-green-600 border-green-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "home-cleaning",
        title: "Home Cleaning",
        titleKey: "services.Home Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional home cleaning by verified experts.",
        descKey: "Professional home cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "deep-cleaning",
        title: "Deep Cleaning",
        titleKey: "services.Deep Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional deep cleaning by verified experts.",
        descKey: "Professional deep cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "sofa-cleaning",
        title: "Sofa Cleaning",
        titleKey: "services.Sofa Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional sofa cleaning by verified experts.",
        descKey: "Professional sofa cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "carpet-cleaning",
        title: "Carpet Cleaning",
        titleKey: "services.Carpet Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional carpet cleaning by verified experts.",
        descKey: "Professional carpet cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "office-cleaning",
        title: "Office Cleaning",
        titleKey: "services.Office Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional office cleaning by verified experts.",
        descKey: "Professional office cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "kitchen-cleaning",
        title: "Kitchen Cleaning",
        titleKey: "services.Kitchen Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional kitchen cleaning by verified experts.",
        descKey: "Professional kitchen cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "post-construction-cleaning",
        title: "Post-Construction Cleaning",
        titleKey: "services.Post-Construction Cleaning",
        category: "Cleaning Services",
        categoryId: "cleaning-services",
        desc: "Professional post-construction cleaning by verified experts.",
        descKey: "Professional post-construction cleaning by verified experts.",
        icon: Sparkles,
        color: "bg-cyan-50 text-cyan-600 border-cyan-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "security-guards",
        title: "Security Guards",
        titleKey: "services.Security Guards",
        category: "Security Services",
        categoryId: "security-services",
        desc: "Professional security guards by verified experts.",
        descKey: "Professional security guards by verified experts.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "event-security",
        title: "Event Security",
        titleKey: "services.Event Security",
        category: "Security Services",
        categoryId: "security-services",
        desc: "Professional event security by verified experts.",
        descKey: "Professional event security by verified experts.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "cctv-monitoring",
        title: "CCTV Monitoring",
        titleKey: "services.CCTV Monitoring",
        category: "Security Services",
        categoryId: "security-services",
        desc: "Professional cctv monitoring by verified experts.",
        descKey: "Professional cctv monitoring by verified experts.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "residential-security",
        title: "Residential Security",
        titleKey: "services.Residential Security",
        category: "Security Services",
        categoryId: "security-services",
        desc: "Professional residential security by verified experts.",
        descKey: "Professional residential security by verified experts.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "commercial-security",
        title: "Commercial Security",
        titleKey: "services.Commercial Security",
        category: "Security Services",
        categoryId: "security-services",
        desc: "Professional commercial security by verified experts.",
        descKey: "Professional commercial security by verified experts.",
        icon: ShieldCheck,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "car-wash",
        title: "Car Wash",
        titleKey: "services.Car Wash",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional car wash by verified experts.",
        descKey: "Professional car wash by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "car-detailing",
        title: "Car Detailing",
        titleKey: "services.Car Detailing",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional car detailing by verified experts.",
        descKey: "Professional car detailing by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "tire-change",
        title: "Tire Change",
        titleKey: "services.Tire Change",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional tire change by verified experts.",
        descKey: "Professional tire change by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "battery-jump-start",
        title: "Battery Jump Start",
        titleKey: "services.Battery Jump Start",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional battery jump start by verified experts.",
        descKey: "Professional battery jump start by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "vehicle-inspection",
        title: "Vehicle Inspection",
        titleKey: "services.Vehicle Inspection",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional vehicle inspection by verified experts.",
        descKey: "Professional vehicle inspection by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "roadside-assistance",
        title: "Roadside Assistance",
        titleKey: "services.Roadside Assistance",
        category: "Automotive Services",
        categoryId: "automotive-services",
        desc: "Professional roadside assistance by verified experts.",
        descKey: "Professional roadside assistance by verified experts.",
        icon: Car,
        color: "bg-gray-100 text-gray-800 border-gray-200",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "ac-repair",
        title: "AC Repair",
        titleKey: "services.AC Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional ac repair by verified experts.",
        descKey: "Professional ac repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "refrigerator-repair",
        title: "Refrigerator Repair",
        titleKey: "services.Refrigerator Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional refrigerator repair by verified experts.",
        descKey: "Professional refrigerator repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "washing-machine-repair",
        title: "Washing Machine Repair",
        titleKey: "services.Washing Machine Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional washing machine repair by verified experts.",
        descKey: "Professional washing machine repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "microwave-repair",
        title: "Microwave Repair",
        titleKey: "services.Microwave Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional microwave repair by verified experts.",
        descKey: "Professional microwave repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "water-dispenser-repair",
        title: "Water Dispenser Repair",
        titleKey: "services.Water Dispenser Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional water dispenser repair by verified experts.",
        descKey: "Professional water dispenser repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "led-tv-repair",
        title: "LED TV Repair",
        titleKey: "services.LED TV Repair",
        category: "Appliance Repair",
        categoryId: "appliance-repair",
        desc: "Professional led tv repair by verified experts.",
        descKey: "Professional led tv repair by verified experts.",
        icon: Smartphone,
        color: "bg-blue-50 text-blue-600 border-blue-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "emergency-electrician",
        title: "Emergency Electrician",
        titleKey: "services.Emergency Electrician",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Professional emergency electrician by verified experts.",
        descKey: "Professional emergency electrician by verified experts.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        isEmergency: true
    },
    {
        id: "emergency-plumber",
        title: "Emergency Plumber",
        titleKey: "services.Emergency Plumber",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Professional emergency plumber by verified experts.",
        descKey: "Professional emergency plumber by verified experts.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        isEmergency: true
    },
    {
        id: "lockout-assistance",
        title: "Lockout Assistance",
        titleKey: "services.Lockout Assistance",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Professional lockout assistance by verified experts.",
        descKey: "Professional lockout assistance by verified experts.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        isEmergency: true
    },
    {
        id: "roadside-help",
        title: "Roadside Help",
        titleKey: "services.Roadside Help",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Professional roadside help by verified experts.",
        descKey: "Professional roadside help by verified experts.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        isEmergency: true
    },
    {
        id: "urgent-home-repair",
        title: "Urgent Home Repair",
        titleKey: "services.Urgent Home Repair",
        category: "Emergency Assistance",
        categoryId: "emergency-assistance",
        desc: "Professional urgent home repair by verified experts.",
        descKey: "Professional urgent home repair by verified experts.",
        icon: Siren,
        color: "bg-red-50 text-red-600 border-red-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        isEmergency: true
    },
    {
        id: "home-nursing",
        title: "Home Nursing",
        titleKey: "services.Home Nursing",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Professional home nursing by verified experts.",
        descKey: "Professional home nursing by verified experts.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-600 border-emerald-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "physiotherapy-at-home",
        title: "Physiotherapy at Home",
        titleKey: "services.Physiotherapy at Home",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Professional physiotherapy at home by verified experts.",
        descKey: "Professional physiotherapy at home by verified experts.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-600 border-emerald-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "doctor-visit",
        title: "Doctor Visit",
        titleKey: "services.Doctor Visit",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Professional doctor visit by verified experts.",
        descKey: "Professional doctor visit by verified experts.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-600 border-emerald-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "lab-sample-collection",
        title: "Lab Sample Collection",
        titleKey: "services.Lab Sample Collection",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Professional lab sample collection by verified experts.",
        descKey: "Professional lab sample collection by verified experts.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-600 border-emerald-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "elder-care-service",
        title: "Elder Care Service",
        titleKey: "services.Elder Care Service",
        category: "Health & Medical",
        categoryId: "health-medical",
        desc: "Professional elder care service by verified experts.",
        descKey: "Professional elder care service by verified experts.",
        icon: Stethoscope,
        color: "bg-emerald-50 text-emerald-600 border-emerald-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "solar-panel-installation",
        title: "Solar Panel Installation",
        titleKey: "services.Solar Panel Installation",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Professional solar panel installation by verified experts.",
        descKey: "Professional solar panel installation by verified experts.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "solar-maintenance",
        title: "Solar Maintenance",
        titleKey: "services.Solar Maintenance",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Professional solar maintenance by verified experts.",
        descKey: "Professional solar maintenance by verified experts.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "battery-installation",
        title: "Battery Installation",
        titleKey: "services.Battery Installation",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Professional battery installation by verified experts.",
        descKey: "Professional battery installation by verified experts.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "solar-inspection",
        title: "Solar Inspection",
        titleKey: "services.Solar Inspection",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Professional solar inspection by verified experts.",
        descKey: "Professional solar inspection by verified experts.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "solar-system-upgrade",
        title: "Solar System Upgrade",
        titleKey: "services.Solar System Upgrade",
        category: "Solar Installation",
        categoryId: "solar-installation",
        desc: "Professional solar system upgrade by verified experts.",
        descKey: "Professional solar system upgrade by verified experts.",
        icon: Sun,
        color: "bg-yellow-50 text-yellow-600 border-yellow-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "haircut-service",
        title: "Haircut Service",
        titleKey: "services.Haircut Service",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional haircut service by verified experts.",
        descKey: "Professional haircut service by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "makeup-service",
        title: "Makeup Service",
        titleKey: "services.Makeup Service",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional makeup service by verified experts.",
        descKey: "Professional makeup service by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "facial-treatment",
        title: "Facial Treatment",
        titleKey: "services.Facial Treatment",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional facial treatment by verified experts.",
        descKey: "Professional facial treatment by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 1500,
        
    },
    {
        id: "bridal-makeup",
        title: "Bridal Makeup",
        titleKey: "services.Bridal Makeup",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional bridal makeup by verified experts.",
        descKey: "Professional bridal makeup by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "massage-therapy",
        title: "Massage Therapy",
        titleKey: "services.Massage Therapy",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional massage therapy by verified experts.",
        descKey: "Professional massage therapy by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
        
    },
    {
        id: "manicure-pedicure",
        title: "Manicure & Pedicure",
        titleKey: "services.Manicure & Pedicure",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional manicure & pedicure by verified experts.",
        descKey: "Professional manicure & pedicure by verified experts.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-600 border-pink-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500,
    },
    // 17) Event Management
    {
        id: "catering-food-setup",
        title: "Catering & Food Setup",
        titleKey: "services.Catering & Food Setup",
        category: "Event Management",
        categoryId: "event-management",
        desc: "Professional catering and food arrangement.",
        descKey: "Professional catering and food arrangement.",
        icon: PartyPopper,
        color: "bg-indigo-50 text-indigo-700 border-indigo-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 10000
    },
    {
        id: "decoration-lighting",
        title: "Decoration & Lighting",
        titleKey: "services.Decoration & Lighting",
        category: "Event Management",
        categoryId: "event-management",
        desc: "Event decoration and artistic lighting setup.",
        descKey: "Event decoration and artistic lighting setup.",
        icon: PartyPopper,
        color: "bg-indigo-50 text-indigo-700 border-indigo-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 5000
    },
    {
        id: "photography-videography",
        title: "Photography & Videography",
        titleKey: "services.Photography & Videography",
        category: "Event Management",
        categoryId: "event-management",
        desc: "Professional event coverage and video production.",
        descKey: "Professional event coverage and video production.",
        icon: Camera,
        color: "bg-indigo-50 text-indigo-700 border-indigo-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 8000
    },

    // 18) Transport Services
    {
        id: "house-shifting-movers",
        title: "House Shifting (Movers)",
        titleKey: "services.House Shifting (Movers)",
        category: "Transport Services",
        categoryId: "transport",
        desc: "Reliable household moving and packing services.",
        descKey: "Reliable household moving and packing services.",
        icon: Truck,
        color: "bg-zinc-100 text-zinc-900 border-zinc-300",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 15000
    },
    {
        id: "cargo-delivery",
        title: "Cargo & Delivery",
        titleKey: "services.Cargo & Delivery",
        category: "Transport Services",
        categoryId: "transport",
        desc: "Safe and timely delivery of goods and cargo.",
        descKey: "Safe and timely delivery of goods and cargo.",
        icon: Truck,
        color: "bg-zinc-100 text-zinc-900 border-zinc-300",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },
    {
        id: "inter-city-car-rental",
        title: "Inter-city Car Rental",
        titleKey: "services.Inter-city Car Rental",
        category: "Transport Services",
        categoryId: "transport",
        desc: "Comfortable car rentals for inter-city travel.",
        descKey: "Comfortable car rentals for inter-city travel.",
        icon: Car,
        color: "bg-zinc-100 text-zinc-900 border-zinc-300",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 5000
    },

    // 19) Beauty & Salon
    {
        id: "haircut-styling",
        title: "Haircut & Styling",
        titleKey: "services.Haircut & Styling",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Professional haircut and hair styling at home.",
        descKey: "Professional haircut and hair styling at home.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-700 border-pink-100",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 500
    },
    {
        id: "bridal-party-makeup",
        title: "Bridal/Party Makeup",
        titleKey: "services.Bridal/Party Makeup",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Expert makeup services for brides and parties.",
        descKey: "Expert makeup services for brides and parties.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-700 border-pink-100",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 5000
    },
    {
        id: "skin-care-facials",
        title: "Skin Care & Facials",
        titleKey: "services.Skin Care & Facials",
        category: "Beauty & Salon",
        categoryId: "beauty-salon",
        desc: "Rejuvenating skin treatments and facials.",
        descKey: "Rejuvenating skin treatments and facials.",
        icon: Scissors,
        color: "bg-pink-50 text-pink-700 border-pink-100",
        image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1500
    },

    // 20) Tour & Travel
    {
        id: "international-flight-booking",
        title: "International Flight Booking",
        titleKey: "services.International Flight Booking",
        category: "Tour & Travel",
        categoryId: "tour",
        desc: "Assistance with international flight reservations.",
        descKey: "Assistance with international flight reservations.",
        icon: Layout,
        color: "bg-teal-50 text-teal-700 border-teal-100",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 1000
    },
    {
        id: "tour-packages",
        title: "Tour Packages",
        titleKey: "services.Tour Packages",
        category: "Tour & Travel",
        categoryId: "tour",
        desc: "Curated domestic and international tour packages.",
        descKey: "Curated domestic and international tour packages.",
        icon: Layout,
        color: "bg-teal-50 text-teal-700 border-teal-100",
        image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=400&h=300&fit=crop",
        startingPrice: 20000
    },
    {
        id: "tour-guides",
        title: "Tour Guides",
        titleKey: "services.Tour Guides",
        category: "Tour & Travel",
        categoryId: "tour",
        desc: "Professional guides for local and regional tours.",
        descKey: "Professional guides for local and regional tours.",
        icon: Layout,
        color: "bg-teal-50 text-teal-700 border-teal-100",
        image: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 2000
    },

    // 21) Agriculture
    {
        id: "machinery-equipments",
        title: "Machinery and equipments",
        titleKey: "services.Machinery and equipments",
        category: "Agriculture",
        categoryId: "agriculture",
        desc: "Rental and repair of agricultural machinery.",
        descKey: "Rental and repair of agricultural machinery.",
        icon: Grid,
        color: "bg-lime-50 text-lime-800 border-lime-200",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop",
        startingPrice: 5000
    },
    {
        id: "irrigation-services",
        title: "Irrigation",
        titleKey: "services.Irrigation",
        category: "Agriculture",
        categoryId: "agriculture",
        desc: "Smart irrigation and water management solutions.",
        descKey: "Smart irrigation and water management solutions.",
        icon: Grid,
        color: "bg-lime-50 text-lime-800 border-lime-200",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=400&h=300&fit=crop",
        startingPrice: 3000
    },
    {
        id: "harvesting-services",
        title: "Harvesting",
        titleKey: "services.Harvesting",
        category: "Agriculture",
        categoryId: "agriculture",
        desc: "Professional harvesting and crop processing.",
        descKey: "Professional harvesting and crop processing.",
        icon: Grid,
        color: "bg-lime-50 text-lime-800 border-lime-200",
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400&h=300",
        startingPrice: 4000
    }
];